### ISSUE TITLE
compatibility warning composer 2.0

### ISSUE THREAD

**Issue by bravedave** [varspool/Wrench#133]
There are two deprecation notices appearing when I run composer update see below

This looks like just a tidy up, your library is used by chrome-php which I'm using

Deprecation Notice: Class Wrench\Tests\Protocol\HybiPayloadTest located in ./vendor/wrench/wrench/lib/Wrench/Tests/Payload/HybiPayloadTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Wrench\Tests\SslTest located in ./vendor/wrench/wrench/lib/Wrench/Tests/Util/SslTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201

**Comment by ejunker** [comment]
I think this has been fixed in the master branch which is targeting v3.0.0. There is a `v3.0.0-rc1` tagged but it would be nice if they either backport the fixes to v2 and tag a release or release a final version of 3.0.0

**Comment by GrahamCampbell** [comment]
This package seems abandoned so I am starting a fork at https://github.com/chrome-php/wrench.
