### ISSUE TITLE
SSL-Problem - Reopened

### ISSUE THREAD

**Issue by leviathoskop** [varspool/Wrench#64]
Hello,

the problem is unfotunately not fixed in Version 2.0.4. Therefore im Reopening my current problem.

The problem ist getting more important lately, because more an more browsers consider a connection from an SSL-Url to an "ws"-websocket as harmful and block it!

Original issue:

Hello everybody,

i'm trying to set up a Websocket-Server using "wss"-protocol. Unfortunatetly even though i followed the instructions given in the other issues, i still get the following errors when i try to connect to the Server.

info: Server initialized
info: Wrench\ConnectionManager: Wrench\Connection: 127.0.0.1:59376 (ULajvFIuPPUTFpsJnvdre5Uhb0Glfgrbv1tyfRCYYfvDEwUrtQmL3II2Z3nzI6nzeBM42sg4JmdD9t0ttMOwfH): Connected
notice: Wrench\ConnectionManager: Client connection closed: exception 'Wrench\Exception\CloseException' with message 'Error reading data from socket: Not connected' in X:\xx\Wrench-master\lib\Wrench\Connection.php:400

As set up using the example given in server_ssl.php, except for the fact that i use a manually created certificate. I also fixed the bug mentioned in the previous issue concerning SSL-Problems.

has anyone an idea what is going wrong?

**Comment by dominics** [comment]
Hi @leviathoskop 

Could you please install with the `2.0.6-beta` version constraint? I've fixed a number of issues to do with the ssl context, and I've also fixed the ssl_server.php example file. (See #68 for details.)

**Comment by leviathoskop** [comment]
@dominics 

Thank you very very much, this fix works for me.
I checked it and i can establish a secure connection!

Thank you very much for your efforts!
