### ISSUE TITLE
No Origin Header

### ISSUE THREAD

**Issue by guile** [varspool/Wrench#66]
When I run a Wrench server (inside scripts of patternlab-php), it calls
<code>$server   = new \Wrench\Server('ws://0.0.0.0:'.$port.'/', array());</code>
This starts the server, but it halts execution soon as a request is made, ending with a cascade of errors. I have pasted a screenshot of the exception reported. 

I checked the HTML request being made, but couldn't get why Wrench wouldn't set the <code>$origin</code> variable

![image](https://cloud.githubusercontent.com/assets/82899/5925491/e2075fe6-a689-11e4-8494-e58d1272b242.png)

![image](https://cloud.githubusercontent.com/assets/82899/5925496/e5ee405c-a689-11e4-89bc-ff540a69c26e.png)

![image](https://cloud.githubusercontent.com/assets/82899/5925562/611cab1a-a68a-11e4-9d2d-74b193edf677.png)

**Comment by Alarmfifa** [comment]
Could you explain how you make a request?
As I see, you tried to make get request. Something like this:
>$ curl "http://localhost:8000"

And It's ok, that you get an exception. Because it isn't a websocket request.

**Comment by dominics** [comment]
In the screenshot, your request URL is `http://127.0.0.1:8002`. Rather than requesting that with your browser, you should use a websocket client and connect to `ws://127.0.0.1:8002`.

See `examples/coffeescript/index.html` (recently fixed up).
