### ISSUE TITLE
fail to run the example!!!  php -q server_ssl.php

### ISSUE THREAD

**Issue by samchen123** [varspool/Wrench#81]
Dear all:
When I run the example(server_ssl.php) in Wrench project
I got 
Warning: require(/home/demo/Wrench-master/examples/../../vendor/autoload.php)

Fatal error: require(): Failed opening required '/home/demo/Wrench-master/examples/../../vendor/autoload.php' (include_path='.:/opt/php/lib/php') in /home/demo/Wrench-master/examples/server_ssl.php on line 16

anybody know why......???? or where is the autoload.php
thanks a lot

**Comment by Kern046** [comment]
Do composer install

**Comment by samchen123** [comment]
Great 
Thanks
